version: "3.8"

services:
  jupyter:
    build: .
    image: mlops_jupyter            # Name of the image
    container_name: mlops_jupyter   # Name of the running container
    ports:
      - "8888:8888"
    volumes:
      - ${HOST_VOLUME}:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    restart: unless-stopped